### ISSUE TITLE
Fix: "화면 pop 시 지도 잔상 늦게 사라짐"

### ISSUE THREAD

**Issue by mouse0429** [money-poly/kwangsang#15]
### 문제
지도를 사용하는 화면에서 지도 잔상이 페이지보다 한발 늦게 사라져, 잔상이 남는 것처럼 보이는 문제

### 상세 마일스톤
N/A

### 참고문서
https://github.com/flutter/flutter/issues/122397
https://github.com/flutter/flutter/issues/118498

**Comment by wjlee611** [comment]
해당 이슈는 저도 InAppWebView를 다루면서 겪은 이슈인데요, TLHC 관련 이슈로 알고 있습니다.

Flutter 3.19.2 에서 해결된걸로 알고 있어서 SDK, flutter_google_map를 최신 버전으로 업그레이드하면 해결될지도 모릅니다!
(InAppWebView는 useHybridComposition 옵션을 제공하여 false로 바꾸면 해결되었음)

**Comment by mouse0429** [comment]
오 감사합니다! 관련해서 알아보고 처리해둘게요!
