### ISSUE TITLE
Refactor: "Numberformat -> commaNumberFormatter 변경"

### ISSUE THREAD

**Issue by mouse0429** [money-poly/kwangsang#34]
### 문제
반복적으로 `NumberForamtter("###,###~~~~")` 쓰는게 번거로은 것 같아서 아예 commaNumberFormatter 를 만들었습니다.
추후에 한번에 교체하면 좋을 것 같습니다.

### 상세 마일스톤
- [ ] #32 머지
- [ ] , 구분자 사용을 위한 포맷터 교체

### 참고문서
N/A

**Comment by wjlee611** [comment]
해당 기능 [extenstion](https://github.com/money-poly/kwangsang/pull/33/files#diff-8fee3fdfb79f57a7babee11d2356f1183e5868de67ea6bd38226b18ecc677387)으로 구현해서 PR 올렸습니다!

**Comment by wjlee611** [comment]
<대충 정수>`.price()` 로 쉽게 포메팅 가능합니다~
